apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{SERVICE_NAME}}
spec:
  type: ClusterIP
  ports:
  - port: {{SERVICE_PORT}}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{SERVICE_NAME}}